<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Plivo Assignment Test" duration-ms="14771" started-at="2018-08-08T10:16:28Z" finished-at="2018-08-08T10:16:42Z">
    <groups>
    </groups>
    <test name="Plivo Message Test" duration-ms="14771" started-at="2018-08-08T10:16:28Z" finished-at="2018-08-08T10:16:42Z">
      <class name="com.plivo.tests.MessageTest">
        <test-method status="PASS" signature="getNumbers()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="getNumbers" duration-ms="5445" started-at="2018-08-08T15:46:28Z" description="To find any two numbers from get all Numbers api" finished-at="2018-08-08T15:46:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getNumbers -->
        <test-method status="PASS" signature="sendMessage()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="sendMessage" duration-ms="2190" started-at="2018-08-08T15:46:33Z" description="To send a message from one number to another identified in first test" depends-on-methods="com.plivo.tests.MessageTest.getNumbers" finished-at="2018-08-08T15:46:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendMessage -->
        <test-method status="PASS" signature="readMsgCharge()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="readMsgCharge" duration-ms="2296" started-at="2018-08-08T15:46:35Z" description="To read message charge for above message" depends-on-methods="com.plivo.tests.MessageTest.sendMessage" finished-at="2018-08-08T15:46:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readMsgCharge -->
        <test-method status="PASS" signature="getOutboundRate()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="getOutboundRate" duration-ms="2731" started-at="2018-08-08T15:46:38Z" description="To get outbound rate for above message" depends-on-methods="com.plivo.tests.MessageTest.readMsgCharge" finished-at="2018-08-08T15:46:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getOutboundRate -->
        <test-method status="FAIL" signature="verifyCashCredit()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="verifyCashCredit" duration-ms="2071" started-at="2018-08-08T15:46:40Z" description="Verify that account cash credit should be less than by the deducted amount" depends-on-methods="com.plivo.tests.MessageTest.readMsgCharge" finished-at="2018-08-08T15:46:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unexpectedly cashCredits is greater than msgCharge as cashCredits: 11.20779 and msgCharge: 0.0035 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unexpectedly cashCredits is greater than msgCharge as cashCredits: 11.20779 and msgCharge: 0.0035 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.plivo.tests.MessageTest.verifyCashCredit(MessageTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCashCredit -->
        <test-method status="PASS" signature="verifyMsgAmount()[pri:0, instance:com.plivo.tests.MessageTest@51efea79]" name="verifyMsgAmount" duration-ms="2" started-at="2018-08-08T15:46:42Z" description="Verify the rate and the price deducted for the sending message, should be same" depends-on-methods="com.plivo.tests.MessageTest.getOutboundRate" finished-at="2018-08-08T15:46:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMsgAmount -->
      </class> <!-- com.plivo.tests.MessageTest -->
    </test> <!-- Plivo Message Test -->
  </suite> <!-- Plivo Assignment Test -->
</testng-results>
